### ISSUE TITLE
Add minimal features to demonstrate best practices

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-local_plugin_template#2]
Collect best practices in readme as used

# Work plan

- [ ] A database table to track latest high five (XML configuration) (is there a best practice to use JSON database spec lol?)
  - [ ] Best practice: Ensure all database columns have id primary key, created_at, updated_at, and foreign keys as needed
- [ ] A database table or some way to make a configuration setting for the "high five emoji"
- [ ] A page that is only accessible by admins to show the latest high five
  - [ ] It allows to change the high five emoji, or it links to the settings page for changing the high five emoji (only allow specific emojis from a dropdown don't let them type anything in :-))
    - [ ] Best practice: This (and all) configuration change is logged using Moodle Logging Module for auditability.
- [ ] Has a visible widget that can be added a user's main page they see when they login

**Comment by fulldecent** [comment]
See also 

https://github.com/Raza403/update_certificate

**Comment by fulldecent** [comment]
See also

Looking [at this page](https://github.com/fulldecent/moodle-local_enrollment_tokens/blob/main/assign.php), I'd say it would be a good idea to get up close and personal with [Moodle's Form API](https://moodledev.io/docs/4.5/apis/subsystems/form)! Grunt is used to build amd modules, and we include the build in the distribution.

Here's a good place to refer to when looking at contributing a plugin:
https://moodledev.io/general/community/plugincontribution/checklist

CREDIT TO https://moodle.org/mod/forum/discuss.php?d=462107
