### ISSUE TITLE
Add a database and events

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/moodle-local_plugin_template#5]
The High Five module will include a simple database:

* high_five
  * id
  * created_at timestamp
  * updated_at timestamp
  * user_id link to users table
  * course_id link to courses table (NULL)

And a new event for high_five_event.

This requires the XML file, and a migration.

# Work plan

- [x] Research and document other modules that have a database component
  - [x] https://github.com/danmarsden/moodle-mod_attendance/tree/MOODLE_404_STABLE/db
  - [x] https://github.com/sebsoftnl/moodle-block_coupon/tree/main/db
  - [x] Moodle plugin documentation
- [x] Identify any requirements above that contradict best practice and document it (such as using a timestamp column, calling the column "created_at", etc.
- [x] Implement the .xml and migration for database
- [x] Implement the event
- [ ] Create /logal/high_five/do-high-five.php which is a REST POST route, requires authentication and records a high five
- [ ] Create a new administration page /local/high_five/index.html which requires the admin to login and it shows the latest high five in the database, and allows to create a high five (user_id = logged in admin user) and which triggers the high five event (clicking the button uses javascript REST API to do the high five without leaving the page)
- [x] Update our documentation README to show a screenshot of the admin, document the fetaure
- [x] Update README to cite all best practice documentation and related notes
